name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "npx prisma generate"
dev = "npx prisma migrate deploy && powershell -Command \"Remove-Item -Path '.react-router' -Recurse -Force -ErrorAction SilentlyContinue\" && npm exec react-router dev"
